### PR TITLE
Roland

### PR DESCRIPTION
**Pull request by dallison**
Adds select for mac os and -ltr for linux builds

### CODE REVIEW

**Comment by dallison** [comment]
I verified that this works on Mac OS (both ARM and x86_64) and Ubuntu 22.04.  I don't have an older Ubuntu OS to check out the 20.04 release.

**Comment by poftwaresatent** [comment]
Neat, seems to work!

**Comment by dallison** [comment]
Roland.  I tried adding your user name "poftwaresatent" as a collaborator but it appears the github doesn't know about you.  Nothing found in the search.  Strange.  I'll keep trying

**Comment by poftwaresatent** [comment]
> [...] it appears the github doesn't know about you.

`¯\_(ツ)_/¯`

Weird. But don't worry about it ;)

**Pull request merged**
